services:
  mongo:
    image: mongo:4.4
    container_name: mongo_iu
    ports:
      - "27017:27017"
    networks:
      - fleet-network
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    networks:
      - fleet-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080
    networks:
      - fleet-network
    depends_on:
      - backend

networks:
  fleet-network:
    driver: bridge

volumes:
  mongo-data: